Issue templates
CodandoJuntas/twitterbot pull request #3
Opened 2018-09-03 23:54 UTC by evelynstender

Criação de templates para issues

2018-09-04 12:47 UTC, angolini requested changes
Só o comentário da revisão ortográfica que precisa ser realmente corrigido. O outro é só sugestão

2018-09-04 12:47 UTC, angolini commented on .github/ISSUE_TEMPLATE/reporte-de-bug.md
> +Se possível, adicione screenchots do bug
screenshots

2018-09-04 12:47 UTC, angolini commented on .github/ISSUE_TEMPLATE/solicite-uma-feature.md
> +Uma clara descrição de alternativas para o problema ou feature nova.
Você pode, por favor, elaborar o que você quer dizer com alternativas?

Talvez algo na linha:

Uma descrição dos possíveis caminhos diferentes que o programa possa tomar para atender as suas expectatívas frustradas descritas no item acima. Uma descrição que nos ajude a entender melhor como implementar uma solução.

2018-09-04 21:29 UTC, evelynstender commented on .github/ISSUE_TEMPLATE/reporte-de-bug.md
> +Se possível, adicione screenchots do bug
typo :P
Mas eu vou mudar isso! Thx!

2018-09-04 21:30 UTC, evelynstender commented on .github/ISSUE_TEMPLATE/solicite-uma-feature.md
> +Uma clara descrição de alternativas para o problema ou feature nova.
Pode ser isso! Na verdade eu peguei o template padrão que eles sugerem em inglês e traduzi algumas coisas! Mas o que vc disse faz bastante sentido!

2018-09-04 21:33 UTC, evelynstender commented
@angolini eu já corrigi as coisas que vc apontou :)

2018-09-05 13:11 UTC, angolini approved these changes

2018-09-05 13:13 UTC, angolini commented
É normal isso de adicionar commits no PR em vez de fazer um squash?

2018-09-05 18:06 UTC, evelynstender commented
@angolini então, que eu saiba é bem normal sim... Teoricamente cada commit é pra alguma coisa que vc alterou e aí fica tudo documentado. Quando faz o merge do PR, eu costumo usar uma opção que chama "Squash and merge" que ele faz o squash de todos os commits em 1 só e manda pra branch master um compilado desses commits... Aí na master aparece como um commit só, mas os commits que fiz nesse PR ficam documentados no PR :)

2018-09-05 18:37 UTC, angolini commented
Tá, vou ter que me adequar. Nos projetos open source que eu participo isso seria impraticável. Na minha cabeça é mais comum você criar um histório de git intencionalmente, e um squash de um PR inteiro me parece um sacrilégio até.

Outra coisa que me causa estranheza é o commit log. Tudo commit log pequeno!

2018-09-06 14:18 UTC, barretoana approved these changes

2018-09-06 17:17 UTC, merged